// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKBuild.Data;

#nullable disable

namespace PKBuild.Migrations
{
    [DbContext(typeof(PKBuildDbContext))]
    partial class PKBuildDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PKBuild.Models.BaseStatsPageModel", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("StatId");

                    b.ToTable("Base Stats", (string)null);
                });

            modelBuilder.Entity("PKBuild.Models.ItemPageModel", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemFlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("PKBuild.Models.PokemonPageModel", b =>
                {
                    b.Property<int>("PkmnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alpha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseStatsStatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVSpA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVSpD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EVSpe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVAtk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVDef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVSpA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVSpD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IVSpe")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemsItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PkdxNatNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PkdxRegNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pokeball")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shiny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeraBaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeraOverrideType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PkmnId");

                    b.HasIndex("BaseStatsStatId");

                    b.HasIndex("ItemsItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Pokemon", (string)null);
                });

            modelBuilder.Entity("PKBuild.Models.TeamsPageModel", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserPageModelUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.HasIndex("UserPageModelUserId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("PKBuild.Models.UserPageModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PokemonPageModelTeamsPageModel", b =>
                {
                    b.Property<int>("PokemonPkmnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamsTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonPkmnId", "TeamsTeamId");

                    b.HasIndex("TeamsTeamId");

                    b.ToTable("PokemonPageModelTeamsPageModel");
                });

            modelBuilder.Entity("PKBuild.Models.PokemonPageModel", b =>
                {
                    b.HasOne("PKBuild.Models.BaseStatsPageModel", "BaseStats")
                        .WithMany("Pokemon")
                        .HasForeignKey("BaseStatsStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKBuild.Models.ItemPageModel", "Items")
                        .WithMany("Pokemon")
                        .HasForeignKey("ItemsItemId");

                    b.HasOne("PKBuild.Models.UserPageModel", "User")
                        .WithMany("Pokemon")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseStats");

                    b.Navigation("Items");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKBuild.Models.TeamsPageModel", b =>
                {
                    b.HasOne("PKBuild.Models.UserPageModel", null)
                        .WithMany("Teams")
                        .HasForeignKey("UserPageModelUserId");
                });

            modelBuilder.Entity("PokemonPageModelTeamsPageModel", b =>
                {
                    b.HasOne("PKBuild.Models.PokemonPageModel", null)
                        .WithMany()
                        .HasForeignKey("PokemonPkmnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKBuild.Models.TeamsPageModel", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PKBuild.Models.BaseStatsPageModel", b =>
                {
                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PKBuild.Models.ItemPageModel", b =>
                {
                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PKBuild.Models.UserPageModel", b =>
                {
                    b.Navigation("Pokemon");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
